export const MOCK_BLOG_POST = [
    {
        id: 1,
        title: "Understanding Cat Behavior: Why Your Feline Friend Acts the Way They Do",
        description: "Dive into the curious world of cat behavior, exploring why cats knead, purr, and chase imaginary prey. This article helps pet owners decode their feline's actions and understand how their instincts as hunters shape their daily routines.",
        category: "Cat",
        images: "/images/posts/Understanding Cat Behavior.png",
        profile: "/images/profile/Thompson P.png",
        author: "Thompson P.",
        date: "11 September 2024",
    },
    {
        id: 2,
        title: "The Fascinating World of Cats: Why We Love Our Furry Friends",
        description: "Cats have captivated human hearts for thousands of years. Whether lounging in a sunny spot or playfully chasing a string, these furry companions bring warmth and joy to millions of homes. But what makes cats so special? Let’s dive into the unique traits, behaviors, and quirks that make cats endlessly fascinating.",
        images: "/images/posts/The Fascinating World of Cats.png",
        profile: "/images/profile/Thompson P.png",
        author: "Thompson P.",
        date: "11 September 2024",
    },
    {
        id: 3,
        title: "Finding Motivation: How to Stay Inspired Through Life's Challenges",
        description: "This article explores strategies to maintain motivation when faced with personal or professional challenges. From setting small goals to practicing mindfulness and surrounding yourself with positive influences, it provides actionable tips to reignite your passion and keep moving forward.",
        images: "/images/posts/Finding Motivation.png",
        profile: "/images/profile/Thompson P.png",
        author: "Thompson P.",
        date: "11 September 2024",
    },
    {
        id: 4,
        title: "The Science of the Cat’s Purr: How It Benefits Cats and Humans Alike",
        description: "Discover the fascinating science behind the cat's purr, including its potential healing properties for both cats and humans. Learn how this unique sound is produced and the emotional and physical benefits it brings to both species.",
        images: "/images/posts/The Science of the Cat’s Purr.png",
        profile: "/images/profile/Thompson P.png",
        author: "Thompson P.",
        date: "11 September 2024",
    },
    {
        id: 5,
        title: "Unlocking Creativity: Simple Habits to Spark Inspiration Daily",
        description: "Discover practical ways to nurture creativity in your everyday life. Whether it's through journaling, taking breaks, or exploring new hobbies, this article offers simple yet effective habits to help you tap into inspiration and stay creatively charged.",
        images: "/images/posts/Unlocking Creativity.png",
        profile: "/images/profile/Thompson P.png",
        author: "Thompson P.",
        date: "11 September 2024",
    },
    {
        id: 6,
        title: "Top 10 Health Tips to Keep Your Cat Happy and Healthy",
        description: "This guide offers essential tips on keeping your cat in peak health. Covering topics like proper nutrition, regular vet visits, grooming, and mental stimulation, it’s a must-read for cat owners who want to ensure their pets live long, happy lives.",
        images: "/images/posts/Top 10 Health Tips to Keep Your Cat.png",
        profile: "/images/profile/Thompson P.png",
        author: "Thompson P.",
        date: "11 September 2024",
    },
];